In [1]:
import torch

In [2]:
from models import VQ_SEEDLM
# device = torch.device("cuda" if torch.cuda.is_available() else "cpu")


/home/jgryu/miniconda3/envs/nicc/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
/home/jgryu/miniconda3/envs/nicc/lib/python3.10/site-packages/compressai/models/video/google.py:353: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  @amp.autocast(enabled=False)


In [3]:
model = VQ_SEEDLM(input_size = 16, K = 16, P = 4, dim_encoder=64, scale = 1, shift = 0)

In [4]:
pt = torch.load('/home/jgryu/Weight_compression/VQ_SEEDLM/checkpoint/Meta-Llama-3-8B/mlp_16_row_dataset.pt/size16_K16_P4_batch_size512_total_iter2000000_lr0.0001_seed100/best_mse_model_MSE_0.34361_total_iter_1450000.pth.tar')
model.load_state_dict(pt['state_dict'])

/tmp/ipykernel_1020357/1103951652.py:1: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  pt = torch.load('/home/jgryu/Weight_compression/VQ_SEEDLM/checkpoint/Meta-Llama-3-8B/ml

<All keys matched successfully>

In [17]:
model.state_dict()['vector_quantization.embedding.weight']

tensor([[-0.7159, -7.4310,  0.6568, -2.5971, -3.7430,  3.8038, -0.7851, -2.7941,
          0.9099,  0.7636,  2.3663,  3.8298,  0.2457, -2.9888, -1.2581, -3.5050],
        [ 5.8182,  1.2225, -0.5896,  1.2592, -2.0442, -0.2261, -8.7649, -0.7917,
         -2.7309,  1.4652,  0.3484,  0.7576, -0.9749,  2.0910,  1.7199, -3.4691],
        [-0.9417, -6.7004,  0.3378, -2.4421, -4.2570,  4.0740, -0.9950, -2.5741,
         -0.6422,  0.3914,  1.9598,  2.0479,  2.1110, -4.8077, -0.9402, -3.5114],
        [-0.5549, -6.0014,  0.4058, -2.7521, -4.3982,  2.9628, -0.3560, -4.6006,
         -0.5032, -1.0150,  2.0469,  3.7394,  1.0539, -3.8158, -1.4000, -3.4291],
        [-0.0449, -7.0732,  0.1641, -1.7818, -5.2675,  2.7947,  0.7638, -3.4548,
         -0.6347,  1.1980,  1.5916,  2.5534,  1.0002, -3.1644, -1.5941, -4.1008],
        [ 4.5894,  0.0911, -0.4356,  0.5542, -2.1886, -0.9053, -9.2249, -0.8319,
         -2.4466,  0.7982, -2.4203, -0.0691, -1.9848,  1.9871,  1.7897, -3.5394],
        [-0.7957, -6.9

In [6]:
t = torch.randn(100, 16)
out = model(t)

In [7]:
print(out['x'][0])
print(out['x_hat'][0])

tensor([ 1.4086,  0.0747,  0.8433, -0.0920,  1.1594,  0.4795,  0.6943,  0.5996,
        -0.5091, -0.0785, -1.5397, -0.3716, -0.6352, -0.8390,  0.8185,  0.2475])
tensor([ 0.4692,  0.3023,  0.3288, -0.1461,  0.4714, -0.4177,  0.2513,  0.7993,
         0.1904, -0.0969, -1.2876, -0.1565, -0.2613, -0.9735,  1.3754,  0.1996],
       grad_fn=<SelectBackward0>)


In [13]:
out['min_encoding_indices'].view(100, 4)

tensor([[ 8,  2,  5, 12],
        [ 3,  4, 12, 11],
        [14,  7,  9, 13],
        [ 8,  7, 10,  1],
        [14,  3,  9, 12],
        [ 7,  6, 13, 11],
        [ 2,  8, 13, 11],
        [ 6,  4, 12,  1],
        [ 6,  8, 13, 15],
        [ 0,  7,  9, 10],
        [ 8,  7, 13,  1],
        [ 0,  2,  1,  5],
        [ 8,  7, 10, 13],
        [ 3,  0, 15, 11],
        [ 4,  7, 15,  9],
        [ 2,  6, 13, 12],
        [ 0,  6, 11,  5],
        [ 0,  7,  9,  5],
        [ 2, 14, 10, 15],
        [ 3, 14, 13,  5],
        [ 6,  8,  1, 12],
        [ 7,  4, 11, 15],
        [ 4,  7, 12, 10],
        [ 6,  7, 10,  5],
        [14,  0, 10, 11],
        [ 2,  4,  5, 11],
        [ 8,  3, 10,  5],
        [14,  6,  9, 11],
        [ 6,  8, 11, 13],
        [ 7,  8,  1, 13],
        [14,  0,  9, 11],
        [ 8,  7,  1, 13],
        [ 7,  6, 15,  5],
        [ 0,  2, 10, 13],
        [ 4,  7,  1,  5],
        [ 7,  6, 15, 13],
        [ 2,  0, 12,  1],
        [ 6,  7,  9, 11],
        [ 8,

In [14]:
out['perplexity']

tensor(15.7193)

In [58]:
import numpy as np
l = []
for i in range(256):
    x_shift = torch.randn(100, 12, 1)
    z_q = torch.randn(100, 12, 4)
    coefficient = torch.matmul(torch.linalg.pinv(z_q), x_shift)
    x_hat  = torch.matmul(z_q, coefficient)
    l.append(((x_shift - x_hat)**2).mean())
print(np.array(l).min(), np.array(l).max())

0.5805316 0.75221896


In [48]:
z_q = torch.randn(100, 4, 16)  # 랜덤 텐서 생성
z_q_pinv = torch.linalg.pinv(z_q)  # 유사 역행렬 계산
result = torch.matmul(z_q, z_q_pinv)[0]  # 첫 번째 배치 결과

print(result)  # 크기 (16, 16)

tensor([[ 1.0000e+00,  9.6858e-08, -4.3772e-08,  2.9802e-08],
        [ 8.5682e-08,  1.0000e+00, -2.6263e-07, -2.0862e-07],
        [-1.3271e-07, -6.5193e-08,  1.0000e+00, -1.2480e-07],
        [-1.5646e-07, -1.7881e-07,  6.0536e-08,  1.0000e+00]])


In [36]:
print(x_shift.shape)
print(x_hat.shape)

torch.Size([100, 16, 1])
torch.Size([100, 16, 1])


In [33]:
torch.linalg.pinv(z_q).shape

torch.Size([100, 4, 16])

In [50]:
((x_shift - x_hat)**2).mean()

tensor(7.9380e-14)